### ISSUE TITLE
Where is original locale? 

### ISSUE THREAD

**Issue by ChangJoo-Park** [Akryum/vue-cli-locale-fr#1]
Hello @Akryum! 
It is awesome plugin for Vue CLI user.
I want to make Korean version of this. Where can I find english version?

**Comment by Akryum** [comment]
Here: https://github.com/vuejs/vue-cli/blob/feat-ui/packages/%40vue/cli/locales/en.json

**Comment by ChangJoo-Park** [comment]
Thanks @Akryum . 
with your guide, I create repo  https://github.com/vuejs-kr/vue-cli-locale-kr

How can I testing kr.json locale?

**Comment by Akryum** [comment]
1. Publish the package to npm
2. Clone [vue-cli](https://github.com/vuejs/vue-cli)
3. Checkout `feat-ui` branch
4. `yarn`
5. Follow the instructions in `packages/@vue/cli-ui` and `packages/@vue/cli-ui-addon-webpack`

**Comment by ChangJoo-Park** [comment]
1. I published package to npm [here](https://www.npmjs.com/package/vue-cli-locale-kr)
2, 3 are OK.

I'll try 4~5 steps. Thanks @Akryum :) 
I want to run Vue CLI UI in Korea :)

**Comment by coderdiaz** [comment]
I create repo for Spanish translation 👍 
https://github.com/coderdiaz/vue-cli-locale-es

And I published the package in npm :) https://www.npmjs.com/package/vue-cli-locale-es 🎉 
It works. Thanks @Akryum :)

**Comment by ChangJoo-Park** [comment]
I saw Korean locale in Vue CLI UI. Thanks @Akryum. 
I close this issue
